// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0m8zKveokjReaZeiIEFuW4HyYet1CwM',
    appId: '1:1060685027516:web:105bf6fe828c06613398b9',
    messagingSenderId: '1060685027516',
    projectId: 'merantieats',
    authDomain: 'merantieats.firebaseapp.com',
    storageBucket: 'merantieats.appspot.com',
    measurementId: 'G-45YDDP6VSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDKmrIqrS2EPI5uttWEmLZcb6ZHeMQSY',
    appId: '1:1060685027516:android:60776737983ca6f13398b9',
    messagingSenderId: '1060685027516',
    projectId: 'merantieats',
    storageBucket: 'merantieats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdeUwXV9Gen8jab-qW0d_T8CokLm_u1Y',
    appId: '1:1060685027516:ios:8a97245e29eeb41e3398b9',
    messagingSenderId: '1060685027516',
    projectId: 'merantieats',
    storageBucket: 'merantieats.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
